title: Xi-editor
description: >
  A modern editor with a backend written in Rust.

baseurl: ""

markdown: kramdown

plugins:
  - octopress-autoprefixer
  - jekyll-redirect-from
  - jekyll-feed

exclude:
  - vendor

sass:
  style: compressed